# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, E, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER, Z, VLC, exec, vlc
# bindd = SUPER, N, NVIM, exec, uwsm-app -- xdg-terminal-exec -e nvim
# bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
# bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
# bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"
# bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
# bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
# bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
# bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
# bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
# bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
# bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
# bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
# Remove default SUPER + HJKL behavior first
unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L

unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, L

unbind = SUPER SHIFT, W

# Switch workspaces
bindd = SUPER, J, Switch to workspace 1, workspace, 1
bindd = SUPER, K, Switch to workspace 2, workspace, 2
bindd = SUPER, L, Switch to workspace 3, workspace, 3
bindd = SUPER, H, Switch to workspace 4, workspace, 4

# Move active window to workspaces
bindd = SUPER SHIFT, J, Move window to workspace 1, movetoworkspace, 1
bindd = SUPER SHIFT, K, Move window to workspace 2, movetoworkspace, 2
bindd = SUPER SHIFT, L, Move window to workspace 3, movetoworkspace, 3
bindd = SUPER SHIFT, H, Move window to workspace 4, movetoworkspace, 4

# New WiFi shortcut
bindd = SUPER SHIFT, W, Wifi controls, exec, omarchy-launch-wifi
